export const destructionLabels = {
  launch: "Разрушить интерфейс",
  title: "Разрушение интерфейса",
  pistol: "Пистолет",
  shotgun: "Дробовик",
  rifle: "Автомат",
  sniper: "Снайперская винтовка",
  flamethrower: "Огнемёт",
  rocket: "Ракетница",
  grenadeLauncher: "Гранатомёт",
  launchDrone: "Запустить дрон",
  detonateDrone: "Взорвать дрон",
  droneHint: "Дрон: WASD / стрелки · ЛКМ — взорвать · таймер 8 с",
  acid: "Кислотная пушка",
  blackHole: "Пушка чёрных дыр",
  nuclear: "Ядерная бомба",
  laser: "Лазерная пушка",
  wheel: "колесо мыши",
  pause: "Пауза",
  restart: "Восстановить и начать заново",
  exit: "Выйти и восстановить",
  move: "движение",
  fly: "прыжок / удерживать для полёта",
  shoot: "ЛКМ — стрелять",
  grenade: "ПКМ — граната",
  paused: "Пауза",
  pausedHint: "Можно немного передохнуть.",
  resume: "Продолжить",
  complete: "Разрушение завершено!",
  completeHint: "Начнём ещё раз?",
} as const;
